import streamlit as st
import os

# Automatically find path
file_path = os.path.join(os.path.dirname(__file__), "Chad_Intelligence_Brief.md")

if not os.path.exists(file_path):
    st.error("Markdown file not found! Please make sure Chad_Intelligence_Brief.md is in the same folder as app.py")
else:
    st.title("AI-Analysis, I don't promise, we will see.")
    st.header("Investment Intelligence Brief")

    # Read the markdown file
    with open(file_path, "r", encoding="utf-8") as file:
        lines = file.readlines()

    current_section = ""
    content_buffer = ""

    # Iterate and display
    for line in lines:
        line = line.strip()

        # Check for section headers
        if line.startswith("##"):
            # If there was a previous section, display it
            if current_section:
                st.subheader(current_section)
                st.write(content_buffer.strip())
                content_buffer = ""

            # Update the section title (remove '##' and strip)
            current_section = line.replace("##", "").strip()

        elif line.startswith("#"):
            # Country header (optional — could be skipped or displayed)
            st.header(line.replace("#", "").strip())
        else:
            content_buffer += line + "\n"

    # Display the last section
    if current_section:
        st.subheader(current_section)
        st.write(content_buffer.strip())

    st.markdown("---")
    st.caption("Generated by AI Analyst - Based on combined multi-report synthesis")
