import streamlit as st
import pandas as pd

# Load the intelligence brief CSV
file_path = "intelligence_brief_final.csv"  # Update the path if necessary
df = pd.read_csv(file_path)

st.title("AI-Analysis, I don't promise, we will see.")
st.header("Investment Intelligence Brief")

# Display each section with nice formatting
for index, row in df.iterrows():
    st.subheader(row['Section'])
    st.write(row['Content'])

st.markdown("---")
st.caption("Generated by AI Analyst - Based on combined multi-report synthesis (10)")
